name: go_open_container
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

resolution: workspace

dependencies:
  collection: null
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  go_router: ^16.2.0
  nested: null

dev_dependencies:
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0

flutter:
  uses-material-design: true
