name: go_router_pop_scope
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

resolution: workspace

dependencies:
  adaptive_dialog: ^2.4.2
  collection: null
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  go_router: ^16.2.0
  hooks_riverpod: ^2.6.1
  nested: null
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  go_router_builder: null
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
