name: color_contrast_app
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4

resolution: workspace

dependencies:
  core:
    path: ../../packages/core
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  gap: ^3.0.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1

flutter:
  uses-material-design: true
