name: fcm_example
description: "This is working repository"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

resolution: workspace

dependencies:
  app_badge_plus: ^1.1.6
  collection: null
  core:
    path: ../../packages/core
  fcm_config: ^3.6.5
  firebase_core: ^3.10.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_local_notifications: ^18.0.1
  hooks_riverpod: ^2.6.1
  nested: null
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.6
  flutter_test:
    sdk: flutter
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
