name: core
description: "Core"
publish_to: "none"
version: 0.0.1

environment:
  sdk: ^3.10.4
  flutter: ^3.38.5

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  logger:

dev_dependencies:
  flutter_test:
    sdk: flutter
  nilts: ^0.23.1
  pedantic_mono: ^1.29.0
